stages:
  - build
  - deploy

check_rst_syntax:
  stage: build
  tags: [linux, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:3.6-18.04-1.1.0
  script:
    - rst-lint *.rst

build_package:linux_py2:
  stage: build
  tags: [linux, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:2.7-18.04-1.1.0
  script:
    - pip install -e .[test]
    - flake8
    - pytest -m "not (needs_serialport or needs_tcp)"
    - python setup.py sdist
    - python setup.py bdist_wheel
  artifacts:
    expire_in: 1 week
    paths: [dist]

build_package:linux_py3:
  stage: build
  tags: [linux, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:3.6-18.04-1.1.0
  script:
    - pip install -e .[test]
    - flake8
    - pytest -m "not (needs_serialport or needs_tcp)"
    - python setup.py bdist_wheel
  artifacts:
    expire_in: 1 week
    paths: [dist]

build_package:windows_py2:
  stage: build
  tags: [windows, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:2.7.12-32bit-windowsservercore-ltsc2019-1.1.0
  script:
    - pip install -e .[test]
    - flake8
    - pytest -m "not (needs_serialport or needs_tcp)"
    - python setup.py bdist_wheel -q
  artifacts:
    expire_in: 1 week
    paths: [dist]

build_package:windows_py3:
  stage: build
  tags: [windows, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:3.5.4-64bit-windowsservercore-ltsc2019-1.1.0
  script:
    - pip install -e .[test]
    - flake8
    - pytest -m "not (needs_serialport or needs_tcp)"
    - python setup.py bdist_wheel -q
  artifacts:
    expire_in: 1 week
    paths: [dist]

build_docs:
  stage: build
  tags: [linux, docker]
  image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:3.6-18.04-1.1.0
  script:
    - apt-get update && apt-get install -y graphviz
    - python setup.py install
    - pip install -r docs/requirements.txt
    - ./ci/set_git_config.sh
    - sphinx-versioning build -r "$CI_COMMIT_REF_NAME" -w "$CI_COMMIT_REF_NAME" docs docs/_build/html

deploy_staging:
    stage: deploy
    tags: [linux, docker]
    image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:2.7-18.04-1.1.0
    dependencies:
      - build_package:linux_py2
      - build_package:linux_py3
      - build_package:windows_py2
      - build_package:windows_py3
    environment:
      name: $DEVPI_GROUP/staging
      url: https://pypi.sensirion.lokal/$DEVPI_GROUP/staging/sensirion-shdlc-driver
    only:
      - master
      - tags
    script:
      - devpi use https://pypi.sensirion.lokal/$DEVPI_GROUP/staging
      - devpi login $DEVPI_GROUP --password=$DEVPI_PW
      - devpi upload --from-dir dist

deploy_stable:
    stage: deploy
    tags: [linux, docker]
    image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:2.7-18.04-1.1.0
    dependencies:
      - build_package:linux_py2
      - build_package:linux_py3
      - build_package:windows_py2
      - build_package:windows_py3
    environment:
      name: pypi.org
      url: https://pypi.org/project/sensirion-shdlc-driver/
    only:
      - tags
    script:
      - PKG_VERSION=$(grep '^version\s*=\s*['"'"'"]\([0-9\.]*\)["'"'"'].*$' sensirion_shdlc_driver/version.py | sed 's/^version\s*=\s*['"'"'"]\([0-9\.]*\)["'"'"'].*$/\1/')
      - TAG_VERSION=$(git describe --tags)
      - if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then echo "Tag Version ($TAG_VERSION) != Package Version ($PKG_VERSION)" && exit 1; fi
      - pip install twine~=1.12.1
      - twine upload dist/*

deploy_docs:
    stage: deploy
    tags: [linux, docker]
    image: registry.gitlab.sensirion.lokal/sensirion/docker/docker-python:3.6-18.04-1.1.0
    dependencies: []
    only:
      - master
      - tags
    script:
      - apt-get update && apt-get install -y graphviz
      - python setup.py install
      - pip install -r docs/requirements.txt
      - ./ci/set_git_config.sh
      - sphinx-versioning push docs gh-pages .
